Update patch set 1
Patch Set 1:

New version of ryu requires tinyrpc which is not packaged:

from tinyrpc.server import RPCServer
  ImportError: No module named tinyrpc.server

Patch-set: 1