Update patch set 7
Patch Set 7: -Code-Review

> DLRN-build-tripleo fails with:
 > 
 > Error: No Package found for python2-networking-odl
 > 
 > We'd need promotion to get it passing although i guess there is no
 > oooq job in networking-bgpvpn, right?

hmm so looking https://github.com/openstack/networking-bgpvpn/blob/master/.zuul.yaml#L57-L69 jobs exist, so would need to adjust dependency on python-networking-odl for pyver ==2 else python3-networking-odl

Patch-set: 7