Update patch set 3
Patch Set 3:

The build is failing during tests with:

ImportError: No module named openstackclient.identity

So we need to add python-openstackclient as a BuildRequires

Patch-set: 3