Update patch set 1
Patch Set 1:

Ok, so after cleaning my glasses and looking at the traceback again, I got what's going on.

- We pinned networking-bagpipe to a commit that depends on Neutron pre-https://review.openstack.org/343045
- networking-bgpvpn depends on networking-bagpipe, so during its build it takes that code
- ...and fails, because we have an up-to-date Neutron:

 File "/usr/lib/python2.7/site-packages/networking_bagpipe/agent/bagpipe_bgp_agent.py", line 47, in <module>
    from neutron.agent.common import config
ImportError: cannot import name config

So in the end, we still need to fix and unpin networking-bagpipe, then we can fix bgpvpn.

Patch-set: 1
Reviewer: Gerrit User 113 <113@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=0